package pepper.skytech.com.myapplication.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import pepper.skytech.com.myapplication.model.FaceUserName;

import pepper.skytech.com.myapplication.db.FaceUserNameDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig faceUserNameDaoConfig;

    private final FaceUserNameDao faceUserNameDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        faceUserNameDaoConfig = daoConfigMap.get(FaceUserNameDao.class).clone();
        faceUserNameDaoConfig.initIdentityScope(type);

        faceUserNameDao = new FaceUserNameDao(faceUserNameDaoConfig, this);

        registerDao(FaceUserName.class, faceUserNameDao);
    }
    
    public void clear() {
        faceUserNameDaoConfig.clearIdentityScope();
    }

    public FaceUserNameDao getFaceUserNameDao() {
        return faceUserNameDao;
    }

}
